# Generated by Django 5.1.3 on 2024-12-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
